-- =============================================================================
--  منصة التأهيل والتوظيف لمستودع المدينة المنورة الخيري
--  REHAB & EMPLOYMENT PLATFORM
--  -----------------------------------------------------------------------------
--  01_schema_core.sql  :  المستخدمون + نظام الصلاحيات (RBAC) + الجلسات/التوكنات
--  Target              :  Oracle Database 23ai
--  Prefix              :  RE_  (جداول النطاق)   SEC_*  (الصلاحيات)
-- =============================================================================
--  ترتيب التنفيذ: 01 -> 02 -> 03 -> 04 -> 05 -> 06 (راجع 00_install_all.sql)
-- =============================================================================

-- ----------------------------------------------------------------------------
--  جدول المستخدمين الموحّد (كل من يسجّل الدخول: مدير/موظف/مستفيد/شركة/معهد...)
-- ----------------------------------------------------------------------------
CREATE TABLE RE_USERS (
  user_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username         VARCHAR2(120)  NOT NULL,
  email            VARCHAR2(254)  NOT NULL,
  phone            VARCHAR2(20),
  full_name        VARCHAR2(200)  NOT NULL,
  -- المصادقة: كلمة مرور محلية (مُجزّأة) و/أو دخول اجتماعي
  password_hash    VARCHAR2(256),                 -- PBKDF2/Argon2 hash (NULL لو دخول اجتماعي فقط)
  password_salt    VARCHAR2(64),
  auth_provider    VARCHAR2(20)   DEFAULT 'LOCAL'  NOT NULL, -- LOCAL/GOOGLE/FACEBOOK/APPLE
  provider_sub     VARCHAR2(255),                 -- معرّف المستخدم لدى مزوّد الدخول الاجتماعي
  -- حالة الحساب
  status           VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL, -- PENDING/ACTIVE/SUSPENDED/CLOSED
  email_verified   VARCHAR2(1)    DEFAULT 'N'      NOT NULL,
  phone_verified   VARCHAR2(1)    DEFAULT 'N'      NOT NULL,
  -- نوع المستخدم الأساسي (للتوجيه السريع للواجهة)
  user_type        VARCHAR2(20)   DEFAULT 'BENEFICIARY' NOT NULL,
                                  -- ADMIN/STAFF/BENEFICIARY/COMPANY/INSTITUTE/RECRUITER/DONOR
  org_id           NUMBER,        -- يرتبط بمنظمة عند كونه موظف شركة/معهد (FK في 05)
  preferred_lang   VARCHAR2(5)    DEFAULT 'ar'     NOT NULL,
  avatar_url       VARCHAR2(500),
  last_login_at    TIMESTAMP,
  failed_logins    NUMBER         DEFAULT 0        NOT NULL,
  created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  created_by       VARCHAR2(120),
  updated_at       TIMESTAMP,
  updated_by       VARCHAR2(120),
  CONSTRAINT re_users_email_uq   UNIQUE (email),
  CONSTRAINT re_users_status_ck  CHECK (status      IN ('PENDING','ACTIVE','SUSPENDED','CLOSED')),
  CONSTRAINT re_users_type_ck    CHECK (user_type   IN ('ADMIN','STAFF','BENEFICIARY','COMPANY','INSTITUTE','RECRUITER','DONOR')),
  CONSTRAINT re_users_prov_ck    CHECK (auth_provider IN ('LOCAL','GOOGLE','FACEBOOK','APPLE')),
  CONSTRAINT re_users_eflag_ck   CHECK (email_verified IN ('Y','N')),
  CONSTRAINT re_users_pflag_ck   CHECK (phone_verified IN ('Y','N'))
);
CREATE INDEX re_users_type_ix    ON RE_USERS (user_type);
CREATE INDEX re_users_org_ix     ON RE_USERS (org_id);
CREATE UNIQUE INDEX re_users_prov_ix ON RE_USERS (auth_provider, provider_sub);

-- ----------------------------------------------------------------------------
--  الأدوار (RBAC)
-- ----------------------------------------------------------------------------
CREATE TABLE SEC_ROLES (
  role_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  role_code   VARCHAR2(40)  NOT NULL,
  role_name   VARCHAR2(120) NOT NULL,
  description VARCHAR2(400),
  is_system   VARCHAR2(1) DEFAULT 'N' NOT NULL,   -- أدوار النظام لا تُحذف
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT sec_roles_code_uq UNIQUE (role_code)
);

-- ----------------------------------------------------------------------------
--  الصلاحيات الدقيقة (Permissions)  مثال: JOB.CREATE / BENEF.APPROVE
-- ----------------------------------------------------------------------------
CREATE TABLE SEC_PERMISSIONS (
  perm_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  perm_code   VARCHAR2(60)  NOT NULL,
  perm_group  VARCHAR2(40)  NOT NULL,   -- USERS / ORGS / JOBS / TRAINING / BENEF / DONATION / REPORT
  description VARCHAR2(300),
  CONSTRAINT sec_perms_code_uq UNIQUE (perm_code)
);

-- ربط الأدوار بالصلاحيات (Many-to-Many)
CREATE TABLE SEC_ROLE_PERMISSIONS (
  role_id NUMBER NOT NULL,
  perm_id NUMBER NOT NULL,
  CONSTRAINT sec_rp_pk PRIMARY KEY (role_id, perm_id)
);

-- ربط المستخدمين بالأدوار (Many-to-Many)  + نطاق اختياري (منظمة معيّنة)
CREATE TABLE SEC_USER_ROLES (
  user_id    NUMBER NOT NULL,
  role_id    NUMBER NOT NULL,
  scope_org  NUMBER,                       -- يحدد الدور داخل منظمة بعينها (لموظفي الشركات)
  granted_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  granted_by VARCHAR2(120),
  CONSTRAINT sec_ur_pk PRIMARY KEY (user_id, role_id)
);

-- ----------------------------------------------------------------------------
--  التوكنات وجلسات الدخول (لإدارة JWT refresh + إبطال التوكن)
-- ----------------------------------------------------------------------------
CREATE TABLE SEC_TOKENS (
  token_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id       NUMBER NOT NULL,
  token_type    VARCHAR2(15) DEFAULT 'REFRESH' NOT NULL, -- REFRESH/RESET/VERIFY
  token_hash    VARCHAR2(128) NOT NULL,        -- نُخزّن hash التوكن لا قيمته الصريحة
  jti           VARCHAR2(64),                  -- JWT ID للـ access token المرتبط
  expires_at    TIMESTAMP NOT NULL,
  revoked       VARCHAR2(1) DEFAULT 'N' NOT NULL,
  user_agent    VARCHAR2(400),
  ip_address    VARCHAR2(60),
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT sec_tokens_type_ck CHECK (token_type IN ('REFRESH','RESET','VERIFY')),
  CONSTRAINT sec_tokens_rev_ck  CHECK (revoked IN ('Y','N'))
);
CREATE INDEX sec_tokens_user_ix ON SEC_TOKENS (user_id);
CREATE INDEX sec_tokens_hash_ix ON SEC_TOKENS (token_hash);

-- ----------------------------------------------------------------------------
--  رموز التحقق (OTP) للبريد/الجوال
-- ----------------------------------------------------------------------------
CREATE TABLE SEC_OTP (
  otp_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id    NUMBER,
  channel    VARCHAR2(10) NOT NULL,        -- EMAIL/SMS/WHATSAPP
  target     VARCHAR2(254) NOT NULL,       -- البريد أو رقم الجوال
  code_hash  VARCHAR2(128) NOT NULL,
  purpose    VARCHAR2(20) NOT NULL,        -- LOGIN/VERIFY/RESET
  attempts   NUMBER DEFAULT 0 NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  consumed   VARCHAR2(1) DEFAULT 'N' NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT sec_otp_chan_ck CHECK (channel IN ('EMAIL','SMS','WHATSAPP')),
  CONSTRAINT sec_otp_purp_ck CHECK (purpose IN ('LOGIN','VERIFY','RESET'))
);
CREATE INDEX sec_otp_target_ix ON SEC_OTP (target, purpose);

-- ----------------------------------------------------------------------------
--  سجل التدقيق (Audit Log) — لكل عملية حسّاسة
-- ----------------------------------------------------------------------------
CREATE TABLE SEC_AUDIT_LOG (
  audit_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id     NUMBER,
  action      VARCHAR2(60)  NOT NULL,      -- LOGIN/CREATE/UPDATE/DELETE/APPROVE/REJECT...
  entity      VARCHAR2(40),                -- اسم الكيان المتأثّر
  entity_id   NUMBER,
  detail      CLOB,                        -- JSON بتفاصيل العملية
  ip_address  VARCHAR2(60),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX sec_audit_user_ix ON SEC_AUDIT_LOG (user_id, created_at);
CREATE INDEX sec_audit_ent_ix  ON SEC_AUDIT_LOG (entity, entity_id);

PROMPT >> 01_schema_core.sql  تم إنشاء جداول المستخدمين والصلاحيات والتوكنات.
