-- =============================================================================
--  02_schema_entities.sql : المنظمات + المستفيدون + التصنيفات + المهارات + الوثائق
-- =============================================================================

-- ----------------------------------------------------------------------------
--  المنظمات: شركات / معاهد ومراكز تدريب / شركات توظيف / جهات مانحة
--  جدول موحّد بحقل نوع، لتبسيط الاعتماد والعلاقات.
-- ----------------------------------------------------------------------------
CREATE TABLE RE_ORGANIZATIONS (
  org_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  org_type        VARCHAR2(20) NOT NULL,   -- COMPANY/INSTITUTE/RECRUITER/DONOR
  legal_name      VARCHAR2(250) NOT NULL,
  brand_name      VARCHAR2(250),
  cr_number       VARCHAR2(40),            -- رقم السجل التجاري
  unified_number  VARCHAR2(40),            -- الرقم الموحّد 700
  sector          VARCHAR2(100),           -- القطاع (تقنية/صحي/تجزئة...)
  city            VARCHAR2(80),
  region          VARCHAR2(80),
  address         VARCHAR2(400),
  website         VARCHAR2(300),
  phone           VARCHAR2(20),
  email           VARCHAR2(254),
  logo_url        VARCHAR2(500),
  about           CLOB,
  -- حالة الاعتماد لدى الجمعية
  approval_status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL, -- PENDING/APPROVED/REJECTED/SUSPENDED
  approved_by     NUMBER,                  -- user_id للمدير المعتمِد
  approved_at     TIMESTAMP,
  reject_reason   VARCHAR2(600),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  created_by      VARCHAR2(120),
  updated_at      TIMESTAMP,
  CONSTRAINT re_org_type_ck   CHECK (org_type IN ('COMPANY','INSTITUTE','RECRUITER','DONOR')),
  CONSTRAINT re_org_status_ck CHECK (approval_status IN ('PENDING','APPROVED','REJECTED','SUSPENDED'))
);
CREATE INDEX re_org_type_ix   ON RE_ORGANIZATIONS (org_type, approval_status);

-- ----------------------------------------------------------------------------
--  ملفات المستفيدين (يرتبط كل مستفيد بمستخدم في RE_USERS)
-- ----------------------------------------------------------------------------
CREATE TABLE RE_BENEFICIARIES (
  benef_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id           NUMBER NOT NULL,
  national_id       VARCHAR2(20),
  gender            VARCHAR2(6),           -- MALE/FEMALE
  birth_date        DATE,
  marital_status    VARCHAR2(20),
  nationality       VARCHAR2(60),
  city              VARCHAR2(80),
  region            VARCHAR2(80),
  -- التعليم والخبرة
  education_level   VARCHAR2(30),          -- SECONDARY/DIPLOMA/BACHELOR/MASTER/PHD
  major             VARCHAR2(150),         -- التخصص
  graduation_year   NUMBER,
  experience_years  NUMBER DEFAULT 0,
  current_status    VARCHAR2(20) DEFAULT 'SEEKER', -- SEEKER/EMPLOYED/TRAINEE/FRESH_GRAD
  -- الرغبات الوظيفية
  desired_titles    VARCHAR2(400),         -- مسميات مرغوبة (CSV)
  desired_city      VARCHAR2(80),
  desired_min_salary NUMBER,
  willing_relocate  VARCHAR2(1) DEFAULT 'N',
  summary           CLOB,                  -- نبذة/ملخص ذاتي
  -- حالة الاعتماد لدى الجمعية
  approval_status   VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL, -- DRAFT/SUBMITTED/APPROVED/REJECTED
  case_officer_id   NUMBER,                -- موظف الجمعية المسؤول عن الحالة
  approved_at       TIMESTAMP,
  completeness_pct  NUMBER DEFAULT 0,      -- نسبة اكتمال الملف 0-100
  created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP,
  CONSTRAINT re_benef_user_uq   UNIQUE (user_id),
  CONSTRAINT re_benef_edu_ck    CHECK (education_level IN ('SECONDARY','DIPLOMA','BACHELOR','MASTER','PHD')),
  CONSTRAINT re_benef_status_ck CHECK (approval_status IN ('DRAFT','SUBMITTED','APPROVED','REJECTED')),
  CONSTRAINT re_benef_cur_ck    CHECK (current_status IN ('SEEKER','EMPLOYED','TRAINEE','FRESH_GRAD')),
  CONSTRAINT re_benef_gen_ck    CHECK (gender IN ('MALE','FEMALE'))
);
CREATE INDEX re_benef_user_ix    ON RE_BENEFICIARIES (user_id);
CREATE INDEX re_benef_officer_ix ON RE_BENEFICIARIES (case_officer_id);
CREATE INDEX re_benef_city_ix    ON RE_BENEFICIARIES (city);

-- ----------------------------------------------------------------------------
--  شجرة التصنيفات الذكية (التخصصات/المجالات/المؤهلات)
--  هرمية عبر parent_id لدعم: مجال > تخصص فرعي
-- ----------------------------------------------------------------------------
CREATE TABLE RE_CATEGORIES (
  category_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  parent_id    NUMBER,
  cat_type     VARCHAR2(20) NOT NULL,      -- FIELD/QUALIFICATION/SENIORITY/FUNCTION
  code         VARCHAR2(40) NOT NULL,
  name_ar      VARCHAR2(150) NOT NULL,
  name_en      VARCHAR2(150),
  sort_order   NUMBER DEFAULT 0,
  active       VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  CONSTRAINT re_cat_code_uq  UNIQUE (cat_type, code),
  CONSTRAINT re_cat_type_ck  CHECK (cat_type IN ('FIELD','QUALIFICATION','SENIORITY','FUNCTION'))
);
CREATE INDEX re_cat_parent_ix ON RE_CATEGORIES (parent_id);

-- ربط المستفيدين بالتصنيفات (Many-to-Many)
CREATE TABLE RE_BENEFICIARY_CATEGORIES (
  benef_id    NUMBER NOT NULL,
  category_id NUMBER NOT NULL,
  CONSTRAINT re_bc_pk PRIMARY KEY (benef_id, category_id)
);

-- ----------------------------------------------------------------------------
--  المهارات + مهارات المستفيد (بمستوى إتقان)
-- ----------------------------------------------------------------------------
CREATE TABLE RE_SKILLS (
  skill_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name_ar   VARCHAR2(120) NOT NULL,
  name_en   VARCHAR2(120),
  category  VARCHAR2(60),                  -- TECHNICAL/SOFT/LANGUAGE/TOOL
  active    VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  CONSTRAINT re_skill_name_uq UNIQUE (name_ar)
);

CREATE TABLE RE_BENEFICIARY_SKILLS (
  benef_id     NUMBER NOT NULL,
  skill_id     NUMBER NOT NULL,
  proficiency  NUMBER DEFAULT 3 NOT NULL,  -- 1..5
  years        NUMBER DEFAULT 0,
  CONSTRAINT re_bs_pk PRIMARY KEY (benef_id, skill_id),
  CONSTRAINT re_bs_prof_ck CHECK (proficiency BETWEEN 1 AND 5)
);

-- ----------------------------------------------------------------------------
--  الوثائق (سيرة ذاتية / شهادات / مرفقات) — مخزّنة كـ BLOB أو رابط خارجي
-- ----------------------------------------------------------------------------
CREATE TABLE RE_DOCUMENTS (
  doc_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  owner_type   VARCHAR2(20) NOT NULL,      -- BENEFICIARY/ORG/APPLICATION
  owner_id     NUMBER NOT NULL,
  doc_type     VARCHAR2(30) NOT NULL,      -- CV/CERTIFICATE/ID/LICENSE/OTHER
  title        VARCHAR2(200),
  mime_type    VARCHAR2(100),
  file_name    VARCHAR2(260),
  file_size    NUMBER,
  storage_kind VARCHAR2(10) DEFAULT 'BLOB' NOT NULL, -- BLOB/URL
  content      BLOB,
  file_url     VARCHAR2(600),
  uploaded_by  NUMBER,
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT re_doc_owner_ck CHECK (owner_type IN ('BENEFICIARY','ORG','APPLICATION')),
  CONSTRAINT re_doc_kind_ck  CHECK (storage_kind IN ('BLOB','URL'))
);
CREATE INDEX re_doc_owner_ix ON RE_DOCUMENTS (owner_type, owner_id);

PROMPT >> 02_schema_entities.sql  تم إنشاء المنظمات والمستفيدين والتصنيفات والمهارات والوثائق.
