-- =============================================================================
--  03_schema_opportunities.sql : الوظائف + البرامج التدريبية + التبرعات
-- =============================================================================

-- ----------------------------------------------------------------------------
--  الوظائف (تنشئها الشركات/شركات التوظيف، تُعتمد من الجمعية)
-- ----------------------------------------------------------------------------
CREATE TABLE RE_JOBS (
  job_id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  org_id           NUMBER NOT NULL,        -- الجهة صاحبة الوظيفة
  posted_by        NUMBER,                 -- user_id (موظف الشركة)
  title            VARCHAR2(200) NOT NULL,
  function_cat     NUMBER,                 -- RE_CATEGORIES (FUNCTION)
  field_cat        NUMBER,                 -- RE_CATEGORIES (FIELD)
  seniority_cat    NUMBER,                 -- RE_CATEGORIES (SENIORITY)
  description      CLOB,
  requirements     CLOB,
  city             VARCHAR2(80),
  region           VARCHAR2(80),
  work_mode        VARCHAR2(15) DEFAULT 'ONSITE', -- ONSITE/REMOTE/HYBRID
  employment_type  VARCHAR2(15) DEFAULT 'FULL',   -- FULL/PART/CONTRACT/TEMP
  min_education    VARCHAR2(30),           -- يطابق RE_BENEFICIARIES.education_level
  min_experience   NUMBER DEFAULT 0,
  salary_min       NUMBER,
  salary_max       NUMBER,
  vacancies        NUMBER DEFAULT 1 NOT NULL,
  -- ربط الوظيفة بتبرع وظيفي إن وُجد
  donation_id      NUMBER,
  -- النشر والاعتماد
  status           VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
                                  -- DRAFT/PENDING/APPROVED/PUBLISHED/CLOSED/FILLED/REJECTED
  approved_by      NUMBER,
  published_at     TIMESTAMP,
  deadline         DATE,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP,
  CONSTRAINT re_job_mode_ck   CHECK (work_mode IN ('ONSITE','REMOTE','HYBRID')),
  CONSTRAINT re_job_etype_ck  CHECK (employment_type IN ('FULL','PART','CONTRACT','TEMP')),
  CONSTRAINT re_job_status_ck CHECK (status IN ('DRAFT','PENDING','APPROVED','PUBLISHED','CLOSED','FILLED','REJECTED'))
);
CREATE INDEX re_job_org_ix    ON RE_JOBS (org_id, status);
CREATE INDEX re_job_status_ix ON RE_JOBS (status, published_at);

-- مهارات مطلوبة للوظيفة (بوزن للمطابقة)
CREATE TABLE RE_JOB_SKILLS (
  job_id     NUMBER NOT NULL,
  skill_id   NUMBER NOT NULL,
  weight     NUMBER DEFAULT 1 NOT NULL,    -- 1..5 أهمية المهارة في المطابقة
  mandatory  VARCHAR2(1) DEFAULT 'N' NOT NULL,
  CONSTRAINT re_js_pk PRIMARY KEY (job_id, skill_id),
  CONSTRAINT re_js_w_ck CHECK (weight BETWEEN 1 AND 5)
);

-- ----------------------------------------------------------------------------
--  البرامج التدريبية (تنشئها المعاهد/مراكز التدريب)
-- ----------------------------------------------------------------------------
CREATE TABLE RE_TRAINING_PROGRAMS (
  program_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  org_id         NUMBER NOT NULL,          -- المعهد/المركز
  title          VARCHAR2(200) NOT NULL,
  field_cat      NUMBER,                   -- RE_CATEGORIES (FIELD)
  description    CLOB,
  outcomes       CLOB,                     -- مخرجات التدريب
  city           VARCHAR2(80),
  delivery_mode  VARCHAR2(15) DEFAULT 'ONSITE', -- ONSITE/ONLINE/HYBRID
  prog_level     VARCHAR2(20) DEFAULT 'BEGINNER', -- BEGINNER/INTERMEDIATE/ADVANCED (level كلمة محجوزة)
  duration_hours NUMBER,
  seats_total    NUMBER DEFAULT 0 NOT NULL,
  seats_taken    NUMBER DEFAULT 0 NOT NULL,
  -- التكلفة والدعم
  original_fee   NUMBER DEFAULT 0,
  discount_pct   NUMBER DEFAULT 0,         -- 0..100 (نسبة الدعم/الخصم)
  is_free        VARCHAR2(1) DEFAULT 'N' NOT NULL,
  certificate    VARCHAR2(1) DEFAULT 'Y' NOT NULL, -- يمنح شهادة؟
  donation_id    NUMBER,                   -- ربط بتبرع تدريبي
  start_date     DATE,
  end_date       DATE,
  enroll_deadline DATE,
  status         VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
                                  -- DRAFT/PENDING/APPROVED/PUBLISHED/CLOSED/COMPLETED/REJECTED
  approved_by    NUMBER,
  published_at   TIMESTAMP,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at     TIMESTAMP,
  CONSTRAINT re_tp_mode_ck   CHECK (delivery_mode IN ('ONSITE','ONLINE','HYBRID')),
  CONSTRAINT re_tp_lvl_ck    CHECK (prog_level IN ('BEGINNER','INTERMEDIATE','ADVANCED')),
  CONSTRAINT re_tp_disc_ck   CHECK (discount_pct BETWEEN 0 AND 100),
  CONSTRAINT re_tp_seats_ck  CHECK (seats_taken <= seats_total),
  CONSTRAINT re_tp_status_ck CHECK (status IN ('DRAFT','PENDING','APPROVED','PUBLISHED','CLOSED','COMPLETED','REJECTED'))
);
CREATE INDEX re_tp_org_ix    ON RE_TRAINING_PROGRAMS (org_id, status);
CREATE INDEX re_tp_status_ix ON RE_TRAINING_PROGRAMS (status, published_at);

-- ----------------------------------------------------------------------------
--  التبرعات: وظيفي / تدريبي / توظيفي
--  يربط جهة مانحة بعدد وحدات (وظائف أو مقاعد) مع تتبّع المستهلك منها.
-- ----------------------------------------------------------------------------
CREATE TABLE RE_DONATIONS (
  donation_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  donor_org_id   NUMBER NOT NULL,          -- الجهة المتبرّعة (شركة/معهد/شركة توظيف)
  donation_type  VARCHAR2(15) NOT NULL,    -- JOB / TRAINING / RECRUITMENT
  title          VARCHAR2(200) NOT NULL,
  description    CLOB,
  -- تفاصيل الكمية
  target_role    VARCHAR2(150),            -- مثال: "محاسب" / "خدمة عملاء"
  units_pledged  NUMBER NOT NULL,          -- عدد الوظائف/المقاعد المتبرّع بها
  units_consumed NUMBER DEFAULT 0 NOT NULL,
  -- للتبرع التدريبي
  discount_pct   NUMBER,                   -- 50 / 100 ...
  monetary_value NUMBER,                   -- قيمة تقديرية للتبرع (للتقارير)
  valid_from     DATE,
  valid_to       DATE,
  status         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL, -- PENDING/APPROVED/ACTIVE/EXHAUSTED/EXPIRED/REJECTED
  approved_by    NUMBER,
  approved_at    TIMESTAMP,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT re_don_type_ck   CHECK (donation_type IN ('JOB','TRAINING','RECRUITMENT')),
  CONSTRAINT re_don_units_ck  CHECK (units_consumed <= units_pledged),
  CONSTRAINT re_don_status_ck CHECK (status IN ('PENDING','APPROVED','ACTIVE','EXHAUSTED','EXPIRED','REJECTED'))
);
CREATE INDEX re_don_donor_ix ON RE_DONATIONS (donor_org_id, status);
CREATE INDEX re_don_type_ix  ON RE_DONATIONS (donation_type, status);

PROMPT >> 03_schema_opportunities.sql  تم إنشاء الوظائف والبرامج التدريبية والتبرعات.
