-- =============================================================================
--  04_schema_applications.sql : الطلبات + المطابقة + المقابلات + العروض
--                               + خطابات التعريف + الإشعارات
-- =============================================================================

-- ----------------------------------------------------------------------------
--  الطلبات (تقديم مستفيد على وظيفة أو برنامج تدريبي) — جدول موحّد
-- ----------------------------------------------------------------------------
CREATE TABLE RE_APPLICATIONS (
  application_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  benef_id        NUMBER NOT NULL,
  target_type     VARCHAR2(10) NOT NULL,   -- JOB / TRAINING
  job_id          NUMBER,                  -- يُملأ إن كان target_type=JOB
  program_id      NUMBER,                  -- يُملأ إن كان target_type=TRAINING
  match_score     NUMBER,                  -- لقطة من درجة المطابقة وقت التقديم 0..100
  cover_note      CLOB,
  source          VARCHAR2(20) DEFAULT 'SELF', -- SELF/STAFF/MATCH_ENGINE
  -- دورة حياة الطلب
  status          VARCHAR2(20) DEFAULT 'SUBMITTED' NOT NULL,
                  -- SUBMITTED/SCREENING/SHORTLISTED/INTERVIEW/OFFER/HIRED/ENROLLED/REJECTED/WITHDRAWN
  status_reason   VARCHAR2(600),
  referred_by     NUMBER,                  -- موظف الجمعية الذي رشّح (إن وُجد)
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP,
  CONSTRAINT re_app_tt_ck     CHECK (target_type IN ('JOB','TRAINING')),
  CONSTRAINT re_app_link_ck   CHECK ( (target_type='JOB'      AND job_id     IS NOT NULL AND program_id IS NULL)
                                   OR (target_type='TRAINING' AND program_id IS NOT NULL AND job_id     IS NULL) ),
  CONSTRAINT re_app_status_ck CHECK (status IN ('SUBMITTED','SCREENING','SHORTLISTED','INTERVIEW','OFFER','HIRED','ENROLLED','REJECTED','WITHDRAWN'))
);
CREATE INDEX re_app_benef_ix ON RE_APPLICATIONS (benef_id, status);
CREATE INDEX re_app_job_ix   ON RE_APPLICATIONS (job_id);
CREATE INDEX re_app_prog_ix  ON RE_APPLICATIONS (program_id);
-- منع التقديم المكرّر على نفس الوظيفة/البرنامج.
-- ملاحظة Oracle: الصفوف التي تكون فيها الأعمدة NULL تُعامل كقيم متمايزة، لذا فهرس
-- مركّب فريد على (benef_id, job_id) لا يمنع تعدّد صفوف التدريب (job_id=NULL) والعكس.
CREATE UNIQUE INDEX re_app_uq_job  ON RE_APPLICATIONS (benef_id, job_id);
CREATE UNIQUE INDEX re_app_uq_prog ON RE_APPLICATIONS (benef_id, program_id);

-- سجل تحوّلات حالة الطلب (Audit trail خاص بالطلب)
CREATE TABLE RE_APPLICATION_EVENTS (
  event_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  application_id NUMBER NOT NULL,
  from_status    VARCHAR2(20),
  to_status      VARCHAR2(20) NOT NULL,
  note           VARCHAR2(600),
  actor_user_id  NUMBER,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);
CREATE INDEX re_appev_ix ON RE_APPLICATION_EVENTS (application_id, created_at);

-- ----------------------------------------------------------------------------
--  نتائج محرك المطابقة (مخزّنة لإعادة الاستخدام والتقارير)
-- ----------------------------------------------------------------------------
CREATE TABLE RE_MATCHES (
  match_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  benef_id      NUMBER NOT NULL,
  target_type   VARCHAR2(10) NOT NULL,     -- JOB / TRAINING
  job_id        NUMBER,
  program_id    NUMBER,
  score         NUMBER NOT NULL,           -- 0..100
  breakdown     CLOB,                      -- JSON: { major, skills, qualification, experience, city, desires }
  computed_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT re_match_tt_ck    CHECK (target_type IN ('JOB','TRAINING')),
  CONSTRAINT re_match_score_ck CHECK (score BETWEEN 0 AND 100)
);
CREATE INDEX re_match_benef_ix ON RE_MATCHES (benef_id, score);
CREATE INDEX re_match_job_ix   ON RE_MATCHES (job_id, score);
CREATE INDEX re_match_prog_ix  ON RE_MATCHES (program_id, score);

-- ----------------------------------------------------------------------------
--  المقابلات
-- ----------------------------------------------------------------------------
CREATE TABLE RE_INTERVIEWS (
  interview_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  application_id NUMBER NOT NULL,
  scheduled_at   TIMESTAMP,
  mode           VARCHAR2(15) DEFAULT 'ONSITE', -- ONSITE/ONLINE/PHONE
  location_url   VARCHAR2(500),            -- عنوان أو رابط اجتماع
  interviewer    VARCHAR2(200),
  status         VARCHAR2(15) DEFAULT 'INVITED' NOT NULL, -- INVITED/CONFIRMED/DONE/NOSHOW/CANCELLED
  result         VARCHAR2(15),             -- PASS/FAIL/PENDING
  notes          CLOB,
  created_by     NUMBER,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT re_iv_mode_ck   CHECK (mode IN ('ONSITE','ONLINE','PHONE')),
  CONSTRAINT re_iv_status_ck CHECK (status IN ('INVITED','CONFIRMED','DONE','NOSHOW','CANCELLED'))
);
CREATE INDEX re_iv_app_ix ON RE_INTERVIEWS (application_id);

-- ----------------------------------------------------------------------------
--  عروض العمل
-- ----------------------------------------------------------------------------
CREATE TABLE RE_OFFERS (
  offer_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  application_id NUMBER NOT NULL,
  salary         NUMBER,
  start_date     DATE,
  details        CLOB,
  status         VARCHAR2(15) DEFAULT 'SENT' NOT NULL, -- SENT/ACCEPTED/DECLINED/EXPIRED
  sent_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  responded_at   TIMESTAMP,
  CONSTRAINT re_offer_status_ck CHECK (status IN ('SENT','ACCEPTED','DECLINED','EXPIRED'))
);
CREATE INDEX re_offer_app_ix ON RE_OFFERS (application_id);

-- ----------------------------------------------------------------------------
--  خطابات التعريف/الترشيح/التوصية مع رقم مرجعي ورمز تحقق QR
-- ----------------------------------------------------------------------------
CREATE TABLE RE_LETTERS (
  letter_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  letter_type   VARCHAR2(20) NOT NULL,     -- INTRO/NOMINATION/RECOMMENDATION
  benef_id      NUMBER NOT NULL,
  ref_number    VARCHAR2(40) NOT NULL,     -- الرقم المرجعي الفريد
  verify_code   VARCHAR2(64) NOT NULL,     -- رمز التحقق (يُضمّن في QR)
  related_org   NUMBER,                    -- جهة موجّه إليها الخطاب (اختياري)
  related_job   NUMBER,
  subject       VARCHAR2(300),
  body          CLOB,                      -- نص الخطاب (قد يولَّد PDF منه)
  pdf_doc_id    NUMBER,                    -- RE_DOCUMENTS للنسخة PDF
  issued_by     NUMBER NOT NULL,           -- موظف الجمعية المُصدر
  issued_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  valid_until   DATE,
  status        VARCHAR2(15) DEFAULT 'ISSUED' NOT NULL, -- ISSUED/REVOKED
  CONSTRAINT re_let_type_ck   UNIQUE (ref_number),
  CONSTRAINT re_let_kind_ck   CHECK (letter_type IN ('INTRO','NOMINATION','RECOMMENDATION')),
  CONSTRAINT re_let_status_ck CHECK (status IN ('ISSUED','REVOKED'))
);
CREATE INDEX re_let_benef_ix  ON RE_LETTERS (benef_id);
CREATE UNIQUE INDEX re_let_vc_ix ON RE_LETTERS (verify_code);

-- ----------------------------------------------------------------------------
--  الإشعارات (متعددة القنوات) + قائمة انتظار الإرسال
-- ----------------------------------------------------------------------------
CREATE TABLE RE_NOTIFICATIONS (
  notif_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id     NUMBER NOT NULL,
  channel     VARCHAR2(12) DEFAULT 'INAPP' NOT NULL, -- INAPP/EMAIL/SMS/WHATSAPP/PUSH
  title       VARCHAR2(200) NOT NULL,
  body        VARCHAR2(1000),
  link        VARCHAR2(500),               -- رابط داخلي عند النقر
  category    VARCHAR2(30),                -- APPLICATION/MATCH/LETTER/SYSTEM/DONATION
  is_read     VARCHAR2(1) DEFAULT 'N' NOT NULL,
  delivery    VARCHAR2(12) DEFAULT 'PENDING' NOT NULL, -- PENDING/SENT/FAILED/READ
  sent_at     TIMESTAMP,
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT re_notif_chan_ck CHECK (channel IN ('INAPP','EMAIL','SMS','WHATSAPP','PUSH')),
  CONSTRAINT re_notif_read_ck CHECK (is_read IN ('Y','N')),
  CONSTRAINT re_notif_del_ck  CHECK (delivery IN ('PENDING','SENT','FAILED','READ'))
);
CREATE INDEX re_notif_user_ix ON RE_NOTIFICATIONS (user_id, is_read, created_at);
CREATE INDEX re_notif_del_ix  ON RE_NOTIFICATIONS (delivery) ;

PROMPT >> 04_schema_applications.sql  تم إنشاء الطلبات والمطابقة والمقابلات والعروض والخطابات والإشعارات.
