-- =============================================================================
--  18_messaging.sql : شات داخلي + إشعارات بين الأطراف
--  ينفّذ مرّة واحدة. عبارات DDL مستقلّة، ثم كتلة ORDS.
-- =============================================================================

CREATE TABLE RE_MESSAGES (
  message_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  from_user      NUMBER NOT NULL,
  to_user        NUMBER NOT NULL,
  body           VARCHAR2(2000) NOT NULL,
  application_id NUMBER,
  is_read        VARCHAR2(1) DEFAULT 'N' NOT NULL,
  created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT re_msg_from_fk FOREIGN KEY (from_user) REFERENCES RE_USERS(user_id) ON DELETE CASCADE,
  CONSTRAINT re_msg_to_fk   FOREIGN KEY (to_user)   REFERENCES RE_USERS(user_id) ON DELETE CASCADE
);
CREATE INDEX re_msg_pair_ix ON RE_MESSAGES (from_user, to_user, created_at);
CREATE INDEX re_msg_inbox_ix ON RE_MESSAGES (to_user, is_read);

BEGIN
  -- GET /me/conversations?uid= : قائمة المحادثات مع آخر رسالة وعدد غير المقروء
  ORDS.DEFINE_TEMPLATE(p_module_name=>'rehab.api.v1', p_pattern=>'me/conversations');
  ORDS.DEFINE_HANDLER(p_module_name=>'rehab.api.v1', p_pattern=>'me/conversations', p_method=>'GET',
    p_source_type=>ORDS.source_type_collection_feed, p_source=>q'[
      SELECT p.peer_id, u.full_name AS peer_name, u.user_type AS peer_type,
             (SELECT body FROM RE_MESSAGES m2
               WHERE (m2.from_user=:uid AND m2.to_user=p.peer_id) OR (m2.from_user=p.peer_id AND m2.to_user=:uid)
               ORDER BY created_at DESC FETCH FIRST 1 ROW ONLY) AS last_body,
             (SELECT MAX(created_at) FROM RE_MESSAGES m3
               WHERE (m3.from_user=:uid AND m3.to_user=p.peer_id) OR (m3.from_user=p.peer_id AND m3.to_user=:uid)) AS last_at,
             (SELECT COUNT(*) FROM RE_MESSAGES m4 WHERE m4.to_user=:uid AND m4.from_user=p.peer_id AND m4.is_read='N') AS unread
        FROM (SELECT DISTINCT CASE WHEN from_user=:uid THEN to_user ELSE from_user END AS peer_id
                FROM RE_MESSAGES WHERE from_user=:uid OR to_user=:uid) p
        JOIN RE_USERS u ON u.user_id = p.peer_id
       ORDER BY last_at DESC ]');

  -- GET /messages?uid=&peer= : رسائل محادثة (ويُعلّمها مقروءة)
  ORDS.DEFINE_TEMPLATE(p_module_name=>'rehab.api.v1', p_pattern=>'messages');
  ORDS.DEFINE_HANDLER(p_module_name=>'rehab.api.v1', p_pattern=>'messages', p_method=>'GET',
    p_source_type=>ORDS.source_type_plsql, p_source=>q'[
      DECLARE v CLOB;
      BEGIN
        UPDATE RE_MESSAGES SET is_read='Y' WHERE to_user=:uid AND from_user=:peer AND is_read='N';
        SELECT JSON_ARRAYAGG(JSON_OBJECT(
                 'message_id' VALUE message_id, 'body' VALUE body,
                 'side' VALUE CASE WHEN from_user=:uid THEN 'me' ELSE 'them' END,
                 'created_at' VALUE TO_CHAR(created_at,'YYYY-MM-DD HH24:MI'))
                 ORDER BY created_at) INTO v
          FROM RE_MESSAGES
         WHERE (from_user=:uid AND to_user=:peer) OR (from_user=:peer AND to_user=:uid);
        COMMIT;
        :status_code := 200; HTP.P(NVL(v, '[]'));
      END; ]');

  -- POST /messages : إرسال رسالة + إشعار  body:{from_uid,to_uid,body,application_id}
  ORDS.DEFINE_HANDLER(p_module_name=>'rehab.api.v1', p_pattern=>'messages', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql, p_source=>q'[
      BEGIN
        INSERT INTO RE_MESSAGES(from_user,to_user,body,application_id) VALUES(:from_uid,:to_uid,:body,:application_id);
        INSERT INTO RE_NOTIFICATIONS(user_id,channel,title,body,category,link,delivery)
        VALUES(:to_uid,'INAPP','رسالة جديدة', SUBSTR(:body,1,180),'MESSAGE','/messages?peer='||:from_uid,'SENT');
        COMMIT;
        :status_code := 201; HTP.P('{"ok":true}');
      EXCEPTION WHEN OTHERS THEN :status_code := 400; HTP.P(JSON_OBJECT('error' VALUE SQLERRM));
      END; ]');

  -- GET /me/notifications?uid=
  ORDS.DEFINE_TEMPLATE(p_module_name=>'rehab.api.v1', p_pattern=>'me/notifications');
  ORDS.DEFINE_HANDLER(p_module_name=>'rehab.api.v1', p_pattern=>'me/notifications', p_method=>'GET',
    p_source_type=>ORDS.source_type_collection_feed, p_source=>q'[
      SELECT notif_id, title, body, link, category, is_read, TO_CHAR(created_at,'YYYY-MM-DD HH24:MI') AS created_at
        FROM RE_NOTIFICATIONS WHERE user_id=:uid ORDER BY created_at DESC FETCH FIRST 30 ROWS ONLY ]');

  -- POST /notifications/read  body:{notif_id, uid}
  ORDS.DEFINE_TEMPLATE(p_module_name=>'rehab.api.v1', p_pattern=>'notifications/read');
  ORDS.DEFINE_HANDLER(p_module_name=>'rehab.api.v1', p_pattern=>'notifications/read', p_method=>'POST',
    p_source_type=>ORDS.source_type_plsql, p_source=>q'[
      BEGIN
        UPDATE RE_NOTIFICATIONS SET is_read='Y' WHERE user_id=:uid AND (notif_id=:notif_id OR :notif_id IS NULL);
        COMMIT; :status_code := 200; HTP.P('{"ok":true}');
      END; ]');

  COMMIT;
END;
/
PROMPT >> 18_messaging.sql  تم: الشات الداخلي والإشعارات.
